namespace SpriteKind {
    export const Collectible = SpriteKind.create()
    export const friend = SpriteKind.create()
    export const boss = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Hero.vy == 0) {
        Hero.vy = -200
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Hero,
    [img`
        ........................
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc..........
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        .......fff..............
        ....fffff2f.............
        ..ffeeeee22ff...........
        .ffeeeeee222ff..........
        .feeeefffeeeef..........
        .fffffeee2222ef.........
        fffe222fffffe2f.........
        fffffffffeeefff.....cc..
        fefe44ebbf44eef...ccdc..
        .fee4d4bbfddef..ccddcc..
        ..feee4dddddfeecdddc....
        ...f2222222eeddcdcc.....
        ...f444445e44ddccc......
        ...ffffffffeeee.........
        ...fff...ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff............
        .ffeeeeef22ff...........
        .feeeeffeeeef...........
        .fffffee2222ef..........
        fffe222ffffe2f..........
        ffffffffeeefff..........
        fefe44ebf44eef..........
        .fee4d4bfddef...........
        ..feee4dddee.c..........
        ...f2222eeddeccccccc....
        ...f444e44ddecddddd.....
        ...fffffeeee.ccccc......
        ..ffffffff...c..........
        ..fff..ff...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef............
        .ffffee2222ef...........
        .fe222ffffe2f...........
        fffffffeeefff...........
        ffe44ebf44eef...........
        fee4d41fddef............
        .feee4ddddf.............
        ..fdde444ef.............
        ..fdde22ccc.............
        ...eef22cdc.............
        ...f4444cddc............
        ....fffffcddc...........
        .....fff..cddc..........
        ...........cdc..........
        ............cc..........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc..........
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Hero,
    [img`
        .............................................
        ......ffffff.................................
        ....ffeeeef2f................................
        ...ffeeeef222f...............................
        ...feeeffeeeef...............................
        ...ffffee2222ef..............................
        ...fe222ffffe2f..............................
        ..fffffffeeefff..............................
        ..ffe44ebf44eef..............................
        ..fee4d41fddef...............................
        ...feee4ddddf................................
        ....4dde444ef................................
        ....edde2222f................................
        ....feef4455ff...............................
        ....ffffffffff...............................
        .....ff...fff................................
        `,img`
        .............................................
        ......ffffff...1e............................
        ....ffeeeef2f..1.ee..........................
        ...ffeeeef222f.1...e.........................
        ...feeeffeeeef.1...e.........................
        ...ffffee2222ef1....e........................
        ...fe222ffffe2f1....e........................
        ..fffffffeeefff1.....e.......................
        ..ffe44ebf44eef1.....e.......................
        ..fee4d41fddef.1.....e.......................
        ...feee4ddddfff1....e........................
        ....4dde4444444d....e........................
        ....edde2222fff1...e.........................
        ....feef4455ff.1...e.........................
        ....ffffffffff.1.ee..........................
        .....ff...fff..1e............................
        `,img`
        .............................................
        ......ffffff.......e.........................
        ....ffeeeef2f.....1.ee.......................
        ...ffeeeef222f....1...e......................
        ...feeeffeeeef....1...e......................
        ...ffffee2222ef..1.....e.....................
        ...fe222ffffe2f.1......e.....................
        ..fffffffeeefff.1.......e....................
        ..ffe44ebf44eef1........e....................
        ..fee4d41fddef.1........e....................
        ...feee4ddddfff1.......e.....................
        ....4dde4444444d.......e.....................
        ....edde2222fff.1.....e......................
        ....feef4455ff..1.....e......................
        ....ffffffffff...1..ee.......................
        .....ff...fff.....1e.........................
        `,img`
        .............................................
        ......ffffff.......e.........................
        ....ffeeeef2f.....1.eeee.....................
        ...ffeeeef222f....1.....e....................
        ...feeeffeeeef....1.....e....................
        ...ffffee2222ef..1.......e...................
        ...fe222ffffe2f.1........e...................
        ..fffffffeeefff.1.........e..................
        ..ffe44ebf44eef1..2.......e..................
        ..fee4d41fddef.1..26666665e..................
        ...feee4ddddfff44d2666666e...................
        ....4dde44444444..2......e...................
        ....edde2222fff.1.......e....................
        ....feef4455ff..1.......e....................
        ....ffffffffff...1..eeee.....................
        .....ff...fff.....1e.........................
        `,img`
        .............................................
        ......ffffff.......e.........................
        ....ffeeeef2f.....1.ee.......................
        ...ffeeeef222f....1...e......................
        ...feeeffeeeef....1...e......................
        ...ffffee2222ef..1.....e.....................
        ...fe222ffffe2f.1......e.....................
        ..fffffffeeefff.1.......e....................
        ..ffe44ebf44eef1........e....................
        ..fee4d41fddef.1........e....................
        ...feee4ddddfff1.......e.....................
        ....4dde4444444d.......e.....................
        ....edde2222fff.1.....e......................
        ....feef4455ff..1.....e......................
        ....ffffffffff...1..ee.......................
        .....ff...fff.....1e.........................
        `,img`
        .............................................
        ......ffffff...1e............................
        ....ffeeeef2f..1.ee..........................
        ...ffeeeef222f.1...e.........................
        ...feeeffeeeef.1...e.........................
        ...ffffee2222ef1....e........................
        ...fe222ffffe2f1....e........................
        ..fffffffeeefff1.....e.......................
        ..ffe44ebf44eef1.....e.......................
        ..fee4d41fddef.1.....e.......................
        ...feee4ddddfff1....e........................
        ....4dde4444444d....e........................
        ....edde2222fff1...e.........................
        ....feef4455ff.1...e.........................
        ....ffffffffff.1.ee..........................
        .....ff...fff..1e............................
        `,img`
        .............................................
        ......ffffff.................................
        ....ffeeeef2f................................
        ...ffeeeef222f...............................
        ...feeeffeeeef...............................
        ...ffffee2222ef..............................
        ...fe222ffffe2f..............................
        ..fffffffeeefff..............................
        ..ffe44ebf44eef..............................
        ..fee4d41fddef...............................
        ...feee4ddddf................................
        ....4dde444ef................................
        ....edde2222f................................
        ....feef4455ff...............................
        ....ffffffffff...............................
        .....ff...fff................................
        `],
    50,
    false
    )
    arrow = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . 2 . . . . . . . . . . . . . . 
        . 2 2 2 . . . . . . . . . . . . 
        . 6 2 6 2 6 2 6 2 6 2 6 . . . . 
        . 2 6 2 6 2 6 2 6 2 6 2 6 1 . . 
        . 6 2 6 2 6 2 6 2 6 2 6 . . . . 
        . 2 2 2 . . . . . . . . . . . . 
        . 2 . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Hero, 75, 0)
    arrow.setVelocity(110, 0)
    animation.runImageAnimation(
    arrow,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        4 . . 2 2 2 . . . . . . . . . . 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        5 5 5 2 6 2 6 2 6 2 6 2 6 5 6 1 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        4 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        5 . . 2 2 2 . . . . . . . . . . 
        4 5 5 6 2 6 2 6 2 6 2 6 5 6 . . 
        4 4 4 2 6 2 6 2 6 2 6 2 6 2 6 1 
        4 5 5 6 2 6 2 6 2 6 2 6 5 6 . . 
        5 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        4 . . 2 2 2 . . . . . . . . . . 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        5 5 5 2 6 2 6 2 6 2 6 5 6 2 6 1 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        4 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        5 . . 2 2 2 . . . . . . . . . . 
        4 5 5 6 2 6 2 6 2 6 5 6 2 6 . . 
        4 4 4 2 6 2 6 2 6 2 6 2 6 2 6 1 
        4 5 5 6 2 6 2 6 2 6 5 6 2 6 . . 
        5 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        4 . . 2 2 2 . . . . . . . . . . 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        5 5 5 2 6 2 6 2 6 5 6 2 6 2 6 1 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        4 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        5 . . 2 2 2 . . . . . . . . . . 
        4 5 5 6 2 6 2 6 5 6 2 6 2 6 . . 
        4 4 4 2 6 2 6 2 6 2 6 2 6 2 6 1 
        4 5 5 6 2 6 2 6 5 6 2 6 2 6 . . 
        5 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        4 . . 2 2 2 . . . . . . . . . . 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        5 5 5 2 6 2 6 5 6 2 6 2 6 2 6 1 
        5 4 4 6 2 6 2 6 2 6 2 6 2 6 . . 
        4 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        5 . . 2 2 2 . . . . . . . . . . 
        4 5 5 6 2 6 5 6 2 6 2 6 2 6 . . 
        4 4 4 2 6 2 6 2 6 2 6 2 6 2 6 1 
        4 5 5 6 2 6 5 6 2 6 2 6 2 6 . . 
        5 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        4 . . 2 2 2 . . . . . . . . . . 
        5 4 4 6 5 6 2 6 2 6 2 6 2 6 . . 
        5 5 5 5 8 5 6 2 6 2 6 2 6 2 6 1 
        5 4 4 6 5 6 2 6 2 6 2 6 2 6 . . 
        4 . . 2 2 2 . . . . . . . . . . 
        . . . 2 . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    false
    )
    info.changeScoreBy(-1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Player, function (sprite, otherSprite) {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite3, otherSprite3) {
    sprites.destroy(Hero, effects.ashes, 500)
    game.reset()
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Hero,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . 4 d d e 4 4 4 e f . . . 
        . . . . e d d e 2 2 2 2 f . . . 
        . . . . f e e f 4 4 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `],
    200,
    true
    )
})
info.onLifeZero(function () {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.friend, function (sprite2, otherSprite2) {
    armor.follow(Hero, 230)
    armor.sayText(" THE BEAST IS NEAR YOU MUST DEFEAT HIM")
    animation.runImageAnimation(
    armor,
    [img`
        .........2.............
        .........22............
        ..........22...........
        ...........2...........
        ...........e...........
        .........bbbbb.........
        .........bbbbb.........
        .........bbbff.........
        .........bbbbf.........
        .........bbbbf.........
        ..........bbbb.........
        .........cccc..........
        ........ccbdcb.........
        ........cbdbcb.........
        ........cccccb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cbdcb.........
        .........ccbcb.........
        .........bfccb1........
        .........bfffb.........
        .........bfffb.........
        .........eeffe.........
        ........e1eebb.........
        .......e1eecc..........
        ......e1eecbc..........
        .....e1eecbbc..........
        ....eeee.cbdc..........
        ...eeee..cddc..........
        ..eeee...cbbc..........
        .effe....cbbc..........
        .eee.....cbdc..........
        .........cddc..........
        .........cbbc..........
        .........cbdc..........
        .........cddc..........
        .........cbbc..........
        .........cbdc..........
        .........cdbc..........
        .........fccf..........
        .........ffff..........
        .........fbbfff........
        `,img`
        .........2.............
        .........22............
        ..........22...........
        ...........2...........
        ...........e...........
        .........bbbbb.........
        .........bbbbb.........
        .........bbbff.........
        .........bbbbf.........
        .........bbbbf.........
        ..........bbbb.........
        .........cccc..........
        ........ccbdcb.........
        ........cbdbcb.........
        ........cccccb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cbdcb.........
        .........ccbcb.........
        .........bfccb1........
        .........bfffb.........
        .........bfffb.........
        .........eeffe.........
        ........e1eebb.........
        .......e1eebbb.........
        ......e1eecccccccc.....
        .....e1eecbbdbbdbc.....
        ....eeee.cbddbddbc.....
        ...eeee.cbcccccbdc.....
        ..eeee..cdc.c.cbbc.....
        .effe..cbdccc.cbdc.....
        .eee..cdbdcc..cddc.....
        .....fbddc....cbbc.....
        ....fbbdc.....fccf.....
        ...fbfbf......ffff.....
        ..fbbbf.......fbbfff...
        ..fbbf........fbbbbf...
        ...fbbf.......ffffff...
        ....fbbf...............
        .....ff................
        .......................
        .......................
        `,img`
        .........2.............
        .........22............
        ..........22...........
        ...........2...........
        ...........e...........
        .........bbbbb.........
        .........bbbbb.........
        .........bbbff.........
        .........bbbbf.........
        .........bbbbf.........
        ..........bbbb.........
        .........cccc..........
        ........ccbdcb.........
        ........cbdbcb.........
        ........cccccb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cbdcb.........
        .........ccbcb.........
        .........bfccb1........
        .........bfffb.........
        .........bfffb.........
        .........eeffe.........
        ........e1eebb.........
        .......e1eebbb.........
        ......e1eecccccccccc...
        .....e1eecbbdcbbdbbc...
        ....eeee.cbddcbddbdc...
        ...eeee..ccccccccddc...
        ..eeee...cbbc...cbbc...
        .effefccccdbc...cbdc...
        .eee1fbddbddc...cddc...
        ...f1fbbdbbbc...cbbc...
        ...fffccccccc...cddc...
        ...ff...........ffff...
        ................f11ff..
        ................fffff..
        .......................
        .......................
        .......................
        .......................
        .......................
        `,img`
        .........2.............
        .........22............
        ..........22...........
        ...........2...........
        ...........e...........
        .........bbbbb.........
        .........bbbbb.........
        .........bbbff.........
        .........bbbbf.........
        .........bbbbf.........
        ..........bbbb.........
        .........cccc..........
        ........ccbdcb.........
        ........cbdbcb.........
        ........cccccb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cddcb.........
        .........cbbcb.........
        .........cdbcb.........
        .........cbdcb.........
        .........ccbcb.........
        .........bfccb1........
        .........bfffb.........
        .........bfffb.........
        .........eeffe.........
        ........e1eebb.........
        .......e1eecc..........
        ......e1eecbc..........
        .....e1eecbbc..........
        ....eeee.cbdc..........
        ...eeee..cddc..........
        ..eeee...cbbc..........
        .effe....cbbc..........
        .eee.....cbdc..........
        .........cddc..........
        .........cbbc..........
        .........cbdc..........
        .........cddc..........
        .........cbbc..........
        .........cbdc..........
        .........cdbc..........
        .........fccf..........
        .........ffff..........
        .........fbbfff........
        `],
    300,
    false
    )
})
let arrow: Sprite = null
let Hero: Sprite = null
let armor: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
let wizard = sprites.create(img`
    . . . . . . . c c c . . . . . . 
    . . . . . . c b 5 c . . . . . . 
    . . . . c c c 5 5 c c c . . . . 
    . . c c b c 5 5 5 5 c c c c . . 
    . c b b 5 b 5 5 5 5 b 5 b b c . 
    . c b 5 5 b b 5 5 b b 5 5 b c . 
    . . f 5 5 5 b b b b 5 5 5 c . . 
    . . f f 5 5 5 5 5 5 5 5 f f . . 
    . . f f f b f e e f b f f f . . 
    . . f f f 1 f b b f 1 f f f . . 
    . . . f f b b b b b b f f . . . 
    . . . e e f e e e e f e e . . . 
    . . e b c b 5 b b 5 b f b e . . 
    . . e e f 5 5 5 5 5 5 f e e . . 
    . . . . c b 5 5 5 5 b c . . . . 
    . . . . . f f f f f f . . . . . 
    `, SpriteKind.friend)
armor = sprites.create(img`
    .........................
    ............222..........
    ............2222.........
    ............222222.......
    ............e..2222......
    .........cccccc2222......
    ........cbbbbbbb222......
    ........cbfffffb222......
    ........cbbbfbbbc22......
    ........cbfbfbfbc22......
    ........cbfbfbfbc22......
    ........cbbbbbbbc22......
    ........cccbcbccc2.......
    ..........cbbbc..2.......
    ..........ccccc..........
    ....ccccc.cdcdc.ccccc....
    ....cdddcccccccccdddc....
    ....cdddcdcc5ccdcdddc....
    ....cdccccbb5bbccccdc....
    ....cccbcbb151bbcbccc....
    .....cbbcb15151bcbbc.....
    .....cbbbcc151ccbbbc.....
    ....cbbbcbbb5bbbcbbbc....
    ...cbbbccbcc5ccbccbbbc...
    ...cbbc.ccddcddcc.cbbc...
    ..ebbc..ccddcddcc..cbbe..
    .cbec...cdcdcdcdc...cecc.
    ffcce...ccddcddcc...eccff
    ffcfe....cdcccdc....efcff
    ...e.....ccdcdcc.....e...
    ...e.....cddcddc.....e...
    ...e.....ccdcdcc.....e...
    ...e....cee555eec....e...
    ...e....cbdcccbdc....e...
    ...e....cddc.cddc....e...
    ...e....cbbc.cbbc....e...
    ...e....cbdc.cbdc....e...
    ..ee....cddc.cddc....ee..
    ..e.....cccc.cccc.....e..
    ..e.....cddc.cddc.....e..
    ..e.....bccb.bccb.....e..
    .ee.....cbbc.cbbc.....ee.
    ff......cddc.cddc......ff
    ff......cbbc.cbbc......ff
    ff......ffff.ffff......ff
    ff......ffff.ffff......ff
    `, SpriteKind.friend)
Hero = sprites.create(img`
    . . . . . . f f f f f f . . . . 
    . . . . f f e e e e f 2 f . . . 
    . . . f f e e e e f 2 2 2 f . . 
    . . . f e e e f f e e e e f . . 
    . . . f f f f e e 2 2 2 2 e f . 
    . . . f e 2 2 2 f f f f e 2 f . 
    . . f f f f f f f e e e f f f . 
    . . f f e 4 4 e b f 4 4 e e f . 
    . . f e e 4 d 4 1 f d d e f . . 
    . . . f e e e 4 d d d d f . . . 
    . . . . f f e e 4 4 4 e f . . . 
    . . . . . 4 d d e 2 2 2 f . . . 
    . . . . . e d d e 2 2 2 f . . . 
    . . . . . f e e f 4 5 5 f . . . 
    . . . . . . f f f f f f . . . . 
    . . . . . . . f f f . . . . . . 
    `, SpriteKind.Player)
let DRAGON = sprites.create(img`
    . f f f . . . . . . . . f f f . 
    f f c . . . . . . . f c b b c . 
    f c c . . . . . . f c b b c . . 
    c f . . . . . . . f b c c c . . 
    c f f . . . . . f f b b c c . . 
    f f f c c . c c f b c b b c . . 
    f f f c c c c c f b c c b c . . 
    . f c 3 c c 3 b c b c c c . . . 
    . c b 3 b c 3 b b c c c c . . . 
    c c b b b b b b b b c c . . . . 
    c 1 1 b b b 1 1 b b b f c . . . 
    f b b b b b b b b b b f c c . . 
    f b c b b b c b b b b f . . . . 
    . f 1 f f f 1 b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `, SpriteKind.Enemy)
let Dragon2 = sprites.create(img`
    . f f f . . . . . . . . f f f . 
    f f c . . . . . . . f c b b c . 
    f c c . . . . . . f c b b c . . 
    c f . . . . . . . f b c c c . . 
    c f f . . . . . f f b b c c . . 
    f f f c c . c c f b c b b c . . 
    f f f c c c c c f b c c b c . . 
    . f c 3 c c 3 b c b c c c . . . 
    . c b 3 b c 3 b b c c c c . . . 
    c c b b b b b b b b c c . . . . 
    c 1 1 b b b 1 1 b b b f c . . . 
    f b b b b b b b b b b f c c . . 
    f b c b b b c b b b b f . . . . 
    . f 1 f f f 1 b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `, SpriteKind.Enemy)
let Boss = sprites.create(img`
    ........................bbbbbbbbbbbbbbbbbbb..................................
    ......................bbb5555555555555555bbbbb...............................
    .....................bb5555555555555555555555bbb......bbc....................
    ....................bb5555555555555555555555555bbb..cbbcc....................
    ...................bb5555555555555555555555555555bccbbccc....................
    ...................b5555555555555555555555555555555ccccc.....................
    ..................bb555b555555555bd55555555555555555cccc.....................
    ..................b5555b555555555bb555555555555555555ccc.....................
    ..................c555555555555555555555555bccc5555555cc.....ccc.............
    ..................c55555bccccc5555555555555ccc1c5555555ccccccbbc.............
    ..................c5555bccccccccb5555555555dcbbc55555555cccbbbcc.............
    ..................c555bddcccccccccb1555555555555555555555ccbccc..............
    ..................c555bcdcccccccccc11b55555555555555555555ccccc..............
    ...................c55ccbcccccccccc11cc5555555555555555555dcccc..............
    ...................c55ccccccccccccc1bccb1555555bb5555555555dcc...............
    ....................c5cccccccccccccccccb1155555b55555555555dcc...............
    ....................c55ccccccccccccccccc1bccccb555555555555ddc...............
    .....................c55cccccccccccccccccccccc555555555555dddccccbbc.........
    ......................c55ccccccb333cc333bcccc555555555555555ddccbbcc.........
    ......................cc55dccc3333bc333333ccb555555555555555ddcccccc.........
    .......................cc555c33333b3333333cc555555555555555dddccccc..........
    ........................ccb533333b33333333c5555555555555555d55dcccc..........
    .........................cb533333b3333333b55d55555555555555555dcccc..........
    .........................cd533333b33b133b55dd5555555555555555dddccc..........
    .................cccc....c5513333333b11355dd55555555555555ddddddcc...........
    ................c55bcc...c5513333333b1155dd5555555555555555dddddcc...........
    ................c55bbc...c5533333333b555dd55555555555555555ddddddccc.........
    ..............ccc55bddc..cb553133133555dd555555555cccc5555dddddddcccccc......
    .............c55bb5bdddc..c55513313555dd5555555555c55ccccddddddddcccccc......
    .............c55dbbbdddcc..cd5555555dbdd5555555555cb5555ccccdddddccccc.......
    .............c555bddbbb5c..cbbbbbbbbbddd5555555ccccbb55bb5dbcddddbccc........
    ..............bbbbddb555ccccddbbbbbddddd5555555c55ccbbbb5555bcddddcc.........
    .............cdd555b555bdbb5dddddddddddd5555555bb5555db5555555cdddc..........
    ...........ccbbb555bbbb5dbb5ddddddddddd555555555bb55ddbccbb555ccddcc.........
    ...........c555bb5555555bb555dddddddddd5555555555bc5ddddddbb555cdddcc........
    ...........c5555b5555555b5555ddddddddd555555555555c55dddbbbb555cbdddc........
    ............cbbb555555dbb555555dddddd5555555555555cc5ddbb5555555bbbddc.......
    .............cbb55555ddb555555555555555555555555555c55db55555555dbbbdcc......
    ..............cccddddddb555555555555555555555555555cc555bbb555555dddddc......
    ................ccddddb55555555555555555555555555555c55555dd555555ddddc......
    .................cddddb5555555555555555555555555555dcc5555dd5555555dddc......
    ..cc.............ccddbd555555555555555555555555555d5dc555dd55555555dddc......
    ..c5bb............ccdbd5555555555555555555555555555ddcc555555555555dddc......
    ..c55b.............ccbd555555555555555555555555555ddddc555555555555ddcc......
    ..cb5bb.............cbdd5555555555555555555555555d5dddcc5555555555dddcc......
    ..cb55b..............cdd555555555555555555555555d55ddddccc5555555dddcc.......
    ..cb55b..............cddd555555555555555555d555d55dddddddccc555ddddcc........
    ..c555b..............cdd55555dd555555555555555dddddddddddddcccccccccc........
    .cb555bb.............cbdd5555dd5555555555555dddddddddddddddddddddddccc.......
    .cb555bb............ccbddd5d55555555dd55555555dddddddddddddddddddddcccc......
    .c55555b...........cccbbddddddd555555555ddd55dddddddddddddddddddddbccc.......
    cb55555b..........cccbbbbdddd55ddd5555ddddddddddddddddddddddddddddbcc........
    cb55555b........bccbbbd5555dd555dd5555d55ddddddddddddddddd55ddddbbbc.........
    c5555555bb....bbbddbb5555555ddddddddddd55dddddddddddddddd55ddddddbbc.........
    c55555555bbbbbbddddc555555555dddddddddddddddddddddddddddd5dd5555ddbc.........
    cd5555555555ddddddc5555555555ddddddddddddddddddddddddddddd55555555dc.........
    cd5555555555dddddcc5555555555dddddddddddddddddddddddddd55d555555555cc........
    cdd55555555ddddddc55555555555dddddddddddddddddddddddddd5555555555555c........
    cddd555555ddddddcc5555555555ddddddddddddddddddddddddddddd55555555555cc.......
    ccddddddddddddddc55555555555ddddddddddddddddddddddddddddd555555555555c.......
    .cddddddddddddddc555555555555dddddddddddddddddddddddddddd555555555555c.......
    .ccddddddddddddcc555555555555ddddddddddddddddddbddddddddd555555555555cc......
    ..ccdddddddddddcc5555555dd55dddddddddddddddddddbdddddddd5d555555555555c......
    ...ccddddddddddccd5555dddddddddddddbbddddddddddbddddddddd5555555555555c......
    ....cccddddddddcddddddddddddddddddbbddddddddddbbbdddddddddd55555555555c......
    ......cccdddddccdddddddddddddddddccccccccccccbbbbddddddddddd555555555dc......
    ........cccccccdddddddddddddddddccc........ccccbbbdddddddddddd5555555dcc.....
    ............ccc555555dddddddddccc.............cccbddddddddddddd55555ddccc....
    .............c55555555ddddddccc..................ccdddddddddddddddddddccc....
    ...........ccdddccd555dddccccc....................ccdddddddddddd5555555dc....
    ..........ccdddccdddddcddcc........................cccddddddddd55555555dcc...
    ..........ccdddcdddccccddc...........................ccccccdddd555ddddccddcc.
    ..........ccccccddcccccdcc...............................ccddddddccddddccddcc
    ...............cdc.....ccc................................cccccdddccddddcddcc
    ...............cc...........................................ccccdddccccdccccc
    ...............................................................ccccc..ccc....
    `, SpriteKind.boss)
wizard.setPosition(26, 22)
Hero.setPosition(26, 22)
DRAGON.setPosition(80, 19)
tiles.placeOnTile(armor, tiles.getTileLocation(146, 15))
tiles.placeOnTile(DRAGON, tiles.getTileLocation(63, 20))
tiles.placeOnTile(Boss, tiles.getTileLocation(197, 15))
scene.cameraFollowSprite(Hero)
Hero.ay = 400
armor.ay = 700
controller.moveSprite(Hero, 100, 0)
game.onUpdate(function () {
    if (arrow.overlapsWith(Boss)) {
        sprites.destroy(Boss, effects.fountain, 500)
    }
})
game.onUpdate(function () {
	
})
game.onUpdateInterval(5000, function () {
	
})
game.onUpdateInterval(5000, function () {
	
})
game.onUpdateInterval(500, function () {
    if (arrow.overlapsWith(DRAGON)) {
        sprites.destroy(DRAGON, effects.fire, 200)
    }
})
game.onUpdateInterval(500, function () {
    if (arrow.overlapsWith(Boss)) {
        sprites.destroy(Boss, effects.fire, 200)
    }
})
game.onUpdateInterval(500, function () {
    animation.runImageAnimation(
    DRAGON,
    [img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c b b b b b b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b c b b b c b b b b f . . . . 
        f b 1 f f f 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . f f f . . . . . . . . . . . 
        f f f c c . . . . . . . . f f f 
        f f c c . . c c . . . f c b b c 
        f f c 3 c c 3 c c f f b b b c . 
        f f b 3 b c 3 b c f b b c c c . 
        . c b b b b b b c f b c b c c . 
        . c b b b b b b c b b c b b c . 
        c b 1 b b b 1 b b b c c c b c . 
        c b b b b b b b b c c c c c . . 
        f b c b b b c b b b b f c . . . 
        f b 1 f f f 1 b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . c c . . c c . . . . . . . . 
        . . c 3 c c 3 c c c . . . . . . 
        . c b 3 b c 3 b c c c . . . . . 
        . c b b b b b b b b f f . . . . 
        c c b b b b b b b b f f . . . . 
        c b 1 b b b 1 b b c f f f . . . 
        c b b b b b b b b f f f f . . . 
        f b c b b b c b c c b b b . . . 
        f b 1 f f f 1 b f c c c c . . . 
        . f b b b b b b f b b c c . . . 
        c c f b b b b b c c b b c . . . 
        c c c f f f f f f c c b b c . . 
        . c c c . . . . . . c c c c c . 
        . . c c c . . . . . . . c c c c 
        . . . . . . . . . . . . . . . . 
        `,img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c b 1 b b b 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `],
    200,
    true
    )
})
